#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fire)
ifeq ($(FIRE_KERNEL_VERSION),6.6)

ifeq ($(FIRE_KERNEL_BUILD_TYPE),source)
FIRE_KERNEL_6_6_PLATFORM_ABS := $(abspath $(FIRE_KERNEL_6_6_PLATFORM))
FIRE_KERNEL_6_6_SOURCE_ABS := $(abspath $(FIRE_KERNEL_6_6_SOURCE))
FIRE_KERNEL_6_6_DIST_DIR_ABS := $(abspath $(FIRE_KERNEL_6_6_DIST_DIR))
FIRE_KERNEL_6_6_OUT_DIR ?= $(FIRE_KERNEL_6_6_PLATFORM_ABS)/out
FIRE_KERNEL_6_6_STAMP := $(FIRE_KERNEL_6_6_DIST_DIR_ABS)/.fire-kernel-6.6.stamp

.PHONY: fire-kernel-6.6 FORCE
fire-kernel-6.6: $(FIRE_KERNEL_6_6_STAMP)

$(FIRE_KERNEL_6_6_STAMP): FORCE
	$(hide) mkdir -p $(dir $@)
	$(hide) cd $(FIRE_KERNEL_6_6_PLATFORM_ABS) && \
		PROJECT=$(FIRE_KERNEL_6_6_PROJECT) \
		MODE=$(FIRE_KERNEL_6_6_MODE) \
		OUT_DIR=$(FIRE_KERNEL_6_6_OUT_DIR) \
		./$(FIRE_KERNEL_6_6_MODULES_DIR)/build.sh
	$(hide) cd $(FIRE_KERNEL_6_6_SOURCE_ABS) && \
		PROJECT=$(FIRE_KERNEL_6_6_PROJECT) \
		MODE=$(FIRE_KERNEL_6_6_MODE) \
		KERNEL_ROOT=$(FIRE_KERNEL_6_6_PLATFORM_ABS) \
		KERNEL_SRC=$(FIRE_KERNEL_6_6_PLATFORM_ABS)/kernel-6.6 \
		DEVICE_MODULES_DIR=$(FIRE_KERNEL_6_6_MODULES_DIR) \
		DEVICE_MODULES_SRC=$(FIRE_KERNEL_6_6_SOURCE_ABS) \
		OUT_DIR=$(FIRE_KERNEL_6_6_OUT_DIR) \
		ROM_ARTIFACTS_DIR=$(FIRE_KERNEL_6_6_DIST_DIR_ABS) \
		SKIP_AK3=1 \
		FIRE66_ROM_DIST_ONLY=1 \
		FIRE66_BOOT_LAYOUT=boot_v4_vendor_boot \
		FIRE66_EXPECT_KERNEL_TEXT_OFFSET=$(FIRE_KERNEL_6_6_EXPECT_TEXT_OFFSET) \
		FIRE66_VENDOR_BOOT_PARTITION_BYTES=$(FIRE_KERNEL_6_6_VENDOR_BOOTIMAGE_PARTITION_SIZE) \
		FIRE66_VENDOR_BOOT_FSTAB=$(abspath $(LOCAL_PATH)/rootdir/etc/fstab.mt6768) \
		FIRST_STAGE_VENDOR_BOOT_MODULES_FILE=$(abspath $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_LIST)) \
		./scripts/package_fire_ak3.sh
	$(hide) touch $@

$(FIRE_KERNEL_6_6_REQUIRED_DIST_FILES) $(FIRE_KERNEL_6_6_VENDOR_MODULES) $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULES): $(FIRE_KERNEL_6_6_STAMP)
	$(hide) test -f $@

$(PRODUCT_OUT)/dtb.img: $(FIRE_KERNEL_6_6_DIST_DTB)
endif

# GKI 6.6 uses the platform kernel module variables from BoardConfigKernel.mk.
# After the source dist exists, Android's standard boot/vendor_boot/vendor
# rules decide what goes into each image.

endif
endif
