#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

FIRE_KERNEL_VERSION := 6.6
FIRE_KERNEL_BUILD_TYPE ?= source

ifneq ($(filter source prebuilt,$(FIRE_KERNEL_BUILD_TYPE)),$(FIRE_KERNEL_BUILD_TYPE))
$(error Unsupported FIRE_KERNEL_BUILD_TYPE "$(FIRE_KERNEL_BUILD_TYPE)"; use source or prebuilt)
endif

FIRE_KERNEL_SOURCE := kernel/xiaomi/fire
FIRE_KERNEL_PREBUILT_IMAGE ?= $(FIRE_KERNEL_SOURCE)/prebuilt/Image

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_NO_GCC := true
TARGET_KERNEL_VERSION := $(FIRE_KERNEL_VERSION)
TARGET_KERNEL_SOURCE := $(FIRE_KERNEL_SOURCE)
TARGET_KERNEL_CONFIG := gki_defconfig
TARGET_KERNEL_CONFIG_EXT := $(TARGET_KERNEL_SOURCE)/fire_rfkill_defconfig
BOARD_KERNEL_IMAGE_NAME := Image

ifeq ($(FIRE_KERNEL_BUILD_TYPE),prebuilt)
TARGET_PREBUILT_KERNEL := $(FIRE_KERNEL_PREBUILT_IMAGE)
endif
