#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

FIRE_KERNEL_VERSION ?= 4.19
FIRE_KERNEL_BUILD_TYPE ?= source

ifneq ($(filter source prebuilt,$(FIRE_KERNEL_BUILD_TYPE)),$(FIRE_KERNEL_BUILD_TYPE))
$(error Unsupported FIRE_KERNEL_BUILD_TYPE "$(FIRE_KERNEL_BUILD_TYPE)"; use source or prebuilt)
endif

FIRE_KERNEL_4_19_SOURCE ?= kernel/xiaomi/fire
FIRE_KERNEL_4_19_PREBUILT_DIR ?= $(FIRE_KERNEL_4_19_SOURCE)/out/fire/AnyKernel3
FIRE_KERNEL_4_19_PREBUILT_IMAGE ?= $(FIRE_KERNEL_4_19_PREBUILT_DIR)/Image.gz-dtb
FIRE_KERNEL_4_19_PREBUILT_DTBO ?= $(FIRE_KERNEL_4_19_PREBUILT_DIR)/dtbo.img

FIRE_KERNEL_6_6_PLATFORM ?= kernel_platform/kernel
FIRE_KERNEL_6_6_MODULES_DIR ?= kernel_device_modules-6.6
FIRE_KERNEL_6_6_SOURCE ?= $(FIRE_KERNEL_6_6_PLATFORM)/$(FIRE_KERNEL_6_6_MODULES_DIR)
FIRE_KERNEL_6_6_PROJECT ?= mgk_64_k66
FIRE_KERNEL_6_6_MODE ?= $(if $(TARGET_BUILD_VARIANT),$(TARGET_BUILD_VARIANT),userdebug)
FIRE_KERNEL_6_6_PREBUILT_DIR ?= $(abspath $(FIRE_KERNEL_6_6_SOURCE)/dist/rom/$(FIRE_KERNEL_6_6_PROJECT).$(FIRE_KERNEL_6_6_MODE))
FIRE_KERNEL_6_6_PREBUILT_IMAGE ?= $(FIRE_KERNEL_6_6_PREBUILT_DIR)/Image.gz
FIRE_KERNEL_6_6_PREBUILT_DTB ?= $(FIRE_KERNEL_6_6_PREBUILT_DIR)/dtb
FIRE_KERNEL_6_6_PREBUILT_DTBO ?= $(FIRE_KERNEL_6_6_PREBUILT_DIR)/dtbo.img
FIRE_KERNEL_6_6_PREBUILT_VENDOR_BOOT ?= $(FIRE_KERNEL_6_6_PREBUILT_DIR)/vendor_boot.img
FIRE_KERNEL_6_6_VENDOR_BOOT ?= false

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_NO_GCC := true

ifeq ($(FIRE_KERNEL_VERSION),4.19)
TARGET_KERNEL_SOURCE := $(FIRE_KERNEL_4_19_SOURCE)
TARGET_KERNEL_CONFIG := fire_defconfig
BOARD_KERNEL_IMAGE_NAME := Image.gz

ifeq ($(FIRE_KERNEL_BUILD_TYPE),prebuilt)
TARGET_PREBUILT_KERNEL := $(FIRE_KERNEL_4_19_PREBUILT_IMAGE)
BOARD_PREBUILT_DTBOIMAGE := $(FIRE_KERNEL_4_19_PREBUILT_DTBO)
endif
else ifeq ($(FIRE_KERNEL_VERSION),6.6)
TARGET_KERNEL_SOURCE := $(FIRE_KERNEL_6_6_SOURCE)
TARGET_KERNEL_CONFIG := $(FIRE_KERNEL_6_6_PROJECT)_defconfig
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_PREBUILT_KERNEL := $(FIRE_KERNEL_6_6_PREBUILT_IMAGE)
BOARD_PREBUILT_DTBIMAGE_DIR := $(FIRE_KERNEL_6_6_PREBUILT_DIR)
BOARD_PREBUILT_DTBOIMAGE := $(FIRE_KERNEL_6_6_PREBUILT_DTBO)

ifeq ($(FIRE_KERNEL_6_6_VENDOR_BOOT),true)
AB_OTA_PARTITIONS += vendor_boot
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMG_HEADER_VERSION := 3
BOARD_PREBUILT_VENDOR_BOOTIMAGE := $(FIRE_KERNEL_6_6_PREBUILT_VENDOR_BOOT)
endif
else
$(error Unsupported FIRE_KERNEL_VERSION "$(FIRE_KERNEL_VERSION)"; use 4.19 or 6.6)
endif
