#
# Copyright (C) 2026 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

FIRE_KERNEL_VERSION ?= 4.19
FIRE_KERNEL_BUILD_TYPE ?= source

ifneq ($(filter source prebuilt,$(FIRE_KERNEL_BUILD_TYPE)),$(FIRE_KERNEL_BUILD_TYPE))
$(error Unsupported FIRE_KERNEL_BUILD_TYPE "$(FIRE_KERNEL_BUILD_TYPE)"; use source or prebuilt)
endif

FIRE_KERNEL_4_19_SOURCE ?= kernel/xiaomi/fire
FIRE_KERNEL_4_19_PREBUILT_DIR ?= $(FIRE_KERNEL_4_19_SOURCE)/out/fire/AnyKernel3
FIRE_KERNEL_4_19_PREBUILT_IMAGE ?= $(FIRE_KERNEL_4_19_PREBUILT_DIR)/Image.gz-dtb
FIRE_KERNEL_4_19_PREBUILT_DTBO ?= $(FIRE_KERNEL_4_19_PREBUILT_DIR)/dtbo.img

FIRE_KERNEL_6_6_PLATFORM ?= kernel_platform/kernel
FIRE_KERNEL_6_6_MODULES_DIR ?= kernel_device_modules-6.6
FIRE_KERNEL_6_6_SOURCE ?= $(FIRE_KERNEL_6_6_PLATFORM)/$(FIRE_KERNEL_6_6_MODULES_DIR)
FIRE_KERNEL_6_6_PROJECT ?= mgk_64_k66
FIRE_KERNEL_6_6_MODE ?= $(if $(TARGET_BUILD_VARIANT),$(TARGET_BUILD_VARIANT),userdebug)
FIRE_KERNEL_6_6_SOURCE_DIST_DIR ?= $(abspath $(FIRE_KERNEL_6_6_SOURCE)/dist/rom/$(FIRE_KERNEL_6_6_PROJECT).$(FIRE_KERNEL_6_6_MODE))
FIRE_KERNEL_6_6_PREBUILT_DIR ?= $(FIRE_KERNEL_6_6_SOURCE_DIST_DIR)
FIRE_KERNEL_6_6_DIST_DIR ?= $(if $(filter prebuilt,$(FIRE_KERNEL_BUILD_TYPE)),$(FIRE_KERNEL_6_6_PREBUILT_DIR),$(FIRE_KERNEL_6_6_SOURCE_DIST_DIR))
FIRE_KERNEL_6_6_IMAGE_COMPRESSION ?= gzip
ifneq ($(filter gzip lz4,$(FIRE_KERNEL_6_6_IMAGE_COMPRESSION)),$(FIRE_KERNEL_6_6_IMAGE_COMPRESSION))
$(error Unsupported FIRE_KERNEL_6_6_IMAGE_COMPRESSION "$(FIRE_KERNEL_6_6_IMAGE_COMPRESSION)"; use gzip or lz4)
endif
FIRE_KERNEL_6_6_IMAGE_NAME := $(if $(filter lz4,$(FIRE_KERNEL_6_6_IMAGE_COMPRESSION)),Image.lz4,Image.gz)
FIRE_KERNEL_6_6_DIST_IMAGE ?= $(FIRE_KERNEL_6_6_DIST_DIR)/$(FIRE_KERNEL_6_6_IMAGE_NAME)
FIRE_KERNEL_6_6_DIST_DTB ?= $(FIRE_KERNEL_6_6_DIST_DIR)/mt6768.dtb
FIRE_KERNEL_6_6_DIST_DTBO ?= $(FIRE_KERNEL_6_6_DIST_DIR)/dtbo.img
FIRE_KERNEL_6_6_PREBUILT_IMAGE ?= $(FIRE_KERNEL_6_6_DIST_IMAGE)
FIRE_KERNEL_6_6_PREBUILT_DTB ?= $(FIRE_KERNEL_6_6_DIST_DTB)
FIRE_KERNEL_6_6_PREBUILT_DTBO ?= $(FIRE_KERNEL_6_6_DIST_DTBO)
FIRE_KERNEL_6_6_SCATTER_SOURCE ?= $(firstword $(wildcard \
    $(DEVICE_PATH)/kernel/6.6/MT6768_Android_scatter.xml \
    $(DEVICE_PATH)/kernel/6.6/MT6768_Android_scatter.txt \
    vendor/xiaomi/fire/MT6768_Android_scatter.xml \
    vendor/xiaomi/fire/MT6768_Android_scatter.txt))
FIRE_KERNEL_6_6_SCATTER_OUTPUT ?= $(if $(FIRE_KERNEL_6_6_SCATTER_SOURCE),$(FIRE_KERNEL_6_6_DIST_DIR)/$(notdir $(FIRE_KERNEL_6_6_SCATTER_SOURCE)))
FIRE_KERNEL_6_6_MODULE_SRC_DIR ?= $(FIRE_KERNEL_6_6_DIST_DIR)/modules/vendor/lib/modules
FIRE_KERNEL_6_6_VENDOR_MODULE_LIST ?= $(DEVICE_PATH)/kernel/6.6/vendor-modules.list
FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_LIST ?= $(DEVICE_PATH)/kernel/6.6/vendor_boot.modules.load
FIRE_KERNEL_6_6_VENDOR_BOOT ?= true
# Stock Fire LK reads requested AVB partitions by physical GPT size in orange
# state. Keep vendor_boot small enough for boot + vendor_boot to fit its heap.
FIRE_KERNEL_6_6_VENDOR_BOOTIMAGE_PARTITION_SIZE ?= 8388608
FIRE_KERNEL_6_6_BOOT_CMDLINE ?=
# Fire stock LK/GZ reaches the ARM64 entry point but currently resets before
# Linux prints anything. Keep the base GKI image replaceable and carry this
# documented early arm64 KASLR switch in vendor_boot while bring-up proves the
# FDT/MMU handoff.
FIRE_KERNEL_6_6_VENDOR_CMDLINE ?= bootopt=64S3,32N2,64N2 nokaslr
FIRE_KERNEL_6_6_BOOTCONFIG ?= androidboot.init_fatal_reboot_target=recovery
# Fire LK enters the ARM64 Image at RAM base + 0x80000. The kernel defconfig
# owns the header value; the packager only verifies the produced Image.
FIRE_KERNEL_6_6_EXPECT_TEXT_OFFSET ?= 0x80000
FIRE_KERNEL_6_6_VENDOR_MODULE_NAMES := $(strip $(shell sed -n '/[.]ko$$/p' $(FIRE_KERNEL_6_6_VENDOR_MODULE_LIST) 2>/dev/null))
FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_NAMES := $(strip $(shell sed -n '/[.]ko$$/p' $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_LIST) 2>/dev/null))
FIRE_KERNEL_6_6_VENDOR_MODULE_LOAD_NAMES := $(filter-out $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_NAMES),$(FIRE_KERNEL_6_6_VENDOR_MODULE_NAMES))
FIRE_KERNEL_6_6_VENDOR_MODULES := $(addprefix $(FIRE_KERNEL_6_6_MODULE_SRC_DIR)/,$(FIRE_KERNEL_6_6_VENDOR_MODULE_NAMES))
FIRE_KERNEL_6_6_VENDOR_BOOT_MODULES := $(addprefix $(FIRE_KERNEL_6_6_MODULE_SRC_DIR)/,$(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_NAMES))
FIRE_KERNEL_6_6_REQUIRED_DIST_FILES := \
    $(FIRE_KERNEL_6_6_DIST_IMAGE) \
    $(FIRE_KERNEL_6_6_DIST_DTB) \
    $(FIRE_KERNEL_6_6_DIST_DTBO)
FIRE_KERNEL_6_6_GENERATED_SCATTER := $(strip $(FIRE_KERNEL_6_6_SCATTER_OUTPUT))
FIRE_KERNEL_6_6_MISSING_DIST_FILES := $(strip $(foreach file,$(FIRE_KERNEL_6_6_REQUIRED_DIST_FILES),$(if $(wildcard $(file)),,$(file))))
FIRE_KERNEL_6_6_MISSING_VENDOR_MODULES := $(strip $(foreach file,$(FIRE_KERNEL_6_6_VENDOR_MODULES),$(if $(wildcard $(file)),,$(file))))
FIRE_KERNEL_6_6_MISSING_VENDOR_BOOT_MODULES := $(strip $(foreach file,$(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULES),$(if $(wildcard $(file)),,$(file))))

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
TARGET_KERNEL_NO_GCC := true

ifeq ($(FIRE_KERNEL_VERSION),4.19)
TARGET_KERNEL_SOURCE := $(FIRE_KERNEL_4_19_SOURCE)
TARGET_KERNEL_CONFIG := fire_defconfig
BOARD_KERNEL_IMAGE_NAME := Image.gz

ifeq ($(FIRE_KERNEL_BUILD_TYPE),prebuilt)
TARGET_PREBUILT_KERNEL := $(FIRE_KERNEL_4_19_PREBUILT_IMAGE)
BOARD_PREBUILT_DTBOIMAGE := $(FIRE_KERNEL_4_19_PREBUILT_DTBO)
endif
else ifeq ($(FIRE_KERNEL_VERSION),6.6)
ifeq ($(FIRE_KERNEL_6_6_VENDOR_MODULE_NAMES),)
$(error Fire 6.6 vendor module list is empty: $(FIRE_KERNEL_6_6_VENDOR_MODULE_LIST))
endif
ifeq ($(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_NAMES),)
$(error Fire 6.6 vendor_boot module list is empty: $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_LIST))
endif
ifeq ($(FIRE_KERNEL_6_6_SCATTER_SOURCE),)
$(error Fire 6.6 scatter source is missing: keep kernel/6.6/MT6768_Android_scatter.xml in this tree or set FIRE_KERNEL_6_6_SCATTER_SOURCE)
endif
ifeq ($(FIRE_KERNEL_BUILD_TYPE),prebuilt)
ifneq ($(FIRE_KERNEL_6_6_MISSING_DIST_FILES),)
$(error Missing Fire 6.6 kernel dist files: $(FIRE_KERNEL_6_6_MISSING_DIST_FILES))
endif
ifneq ($(FIRE_KERNEL_6_6_MISSING_VENDOR_MODULES),)
$(error Missing Fire 6.6 vendor modules: $(FIRE_KERNEL_6_6_MISSING_VENDOR_MODULES))
endif
ifneq ($(FIRE_KERNEL_6_6_MISSING_VENDOR_BOOT_MODULES),)
$(error Missing Fire 6.6 vendor_boot modules: $(FIRE_KERNEL_6_6_MISSING_VENDOR_BOOT_MODULES))
endif
endif
TARGET_KERNEL_SOURCE := $(FIRE_KERNEL_6_6_SOURCE)
TARGET_KERNEL_CONFIG := $(FIRE_KERNEL_6_6_PROJECT)_defconfig
BOARD_KERNEL_IMAGE_NAME := $(FIRE_KERNEL_6_6_IMAGE_NAME)
TARGET_PREBUILT_KERNEL := $(FIRE_KERNEL_6_6_DIST_IMAGE)
BOARD_PREBUILT_DTBIMAGE_DIR := $(FIRE_KERNEL_6_6_DIST_DIR)
BOARD_PREBUILT_DTBOIMAGE := $(FIRE_KERNEL_6_6_DIST_DTBO)
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_BOOT_HEADER_VERSION := 4
BOARD_KERNEL_PAGESIZE := 4096
BOARD_RAMDISK_USE_LZ4 := true
BOARD_USES_GENERIC_KERNEL_IMAGE := true
BOARD_USES_RECOVERY_AS_BOOT := false
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_MOVE_GSI_AVB_KEYS_TO_VENDOR_BOOT := true
GENERIC_KERNEL_CMDLINE := $(FIRE_KERNEL_6_6_BOOT_CMDLINE)
BOARD_KERNEL_CMDLINE := $(FIRE_KERNEL_6_6_VENDOR_CMDLINE)
BOARD_BOOTCONFIG := $(FIRE_KERNEL_6_6_BOOTCONFIG)
BOARD_GKI_SIGNING_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_GKI_SIGNING_ALGORITHM := SHA256_RSA2048
BOARD_DO_NOT_STRIP_VENDOR_MODULES := true
BOARD_DO_NOT_STRIP_VENDOR_RAMDISK_MODULES := true
# AOSP reuses BOARD_MKBOOTIMG_ARGS for boot and vendor_boot. Header v4 keeps
# boot generic, while vendor_boot still records the stock LK load addresses.
BOARD_MKBOOTIMG_ARGS = --base $(BOARD_KERNEL_BASE)
BOARD_MKBOOTIMG_ARGS += --kernel_offset $(BOARD_KERNEL_OFFSET)
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dtb_offset $(BOARD_DTB_OFFSET)
BOARD_MKBOOTIMG_ARGS += --pagesize $(BOARD_KERNEL_PAGESIZE)
BOARD_MKBOOTIMG_ARGS += --header_version $(BOARD_BOOTIMG_HEADER_VERSION)
BOARD_MKBOOTIMG_ARGS += --board ""
BOARD_VENDOR_KERNEL_MODULES += $(FIRE_KERNEL_6_6_VENDOR_MODULES)
BOARD_VENDOR_KERNEL_MODULES_LOAD += $(FIRE_KERNEL_6_6_VENDOR_MODULE_LOAD_NAMES)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES += $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULES)
BOARD_VENDOR_RAMDISK_KERNEL_MODULES_LOAD += $(FIRE_KERNEL_6_6_VENDOR_BOOT_MODULE_NAMES)

ifeq ($(FIRE_KERNEL_6_6_VENDOR_BOOT),true)
AB_OTA_PARTITIONS += vendor_boot
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := $(FIRE_KERNEL_6_6_VENDOR_BOOTIMAGE_PARTITION_SIZE)
BOARD_VENDOR_BOOTIMG_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_AVB_VENDOR_BOOT_KEY_PATH := external/avb/test/data/testkey_rsa2048.pem
BOARD_AVB_VENDOR_BOOT_ALGORITHM := SHA256_RSA2048
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX := 1
BOARD_AVB_VENDOR_BOOT_ROLLBACK_INDEX_LOCATION := 0
endif
else
$(error Unsupported FIRE_KERNEL_VERSION "$(FIRE_KERNEL_VERSION)"; use 4.19 or 6.6)
endif
